#!/usr/bin/env node

require('env-yaml').config();

const app = require('./config/app');

require('./kernel')(() => {
  const work = require('lesswork-cmd');

  const Commands = require('lesswork-framework/Console');

  const AppCommands = app.commands;

  Object.keys(Commands).forEach((name) => {
    work.addCommand(Commands[name]);
  });

  Object.keys(AppCommands).forEach((name) => {
    work.addCommand(require(AppCommands[name]));
  });

  work.onError(function (error, commandName) {
    console.log(`${commandName} reported ${error.message}`);
    process.exit(1);
  });

  work.wireUpWithCommander();

  work.invoke();
}, app.providers.concat(app.workProviders));