#!/usr/bin/env node

require('lesswork-framework/lib/env');

const app = require('lesswork-framework/lib/app')(process.cwd());

const config = require('./config/app');

app({}, function () {
  require('lesswork-framework/src/Work')(config);
}, config.providers.concat(config.workProviders));